### ISSUE TITLE
early token address check

### ISSUE THREAD

**Issue by JackBekket** [daseinsucks/MultisigWIP#2]
https://github.com/daseinsucks/MultisigWIP/blob/8812577e9b2dec91e8c05c3b1092f83220d45ae6/contracts/GnosisSafe.sol#L191

ты абсолютно прав, давай поставим вот тут if else

если адрес подходит, то 
```
success = executePayload(...);
 bool success2 = forwardFees(data);
 else
 success = execute(...);
 bool success2 = true;
 ```

**Comment by daseinsucks** [comment]
https://github.com/daseinsucks/MultisigWIP/blob/9e82202183772a053f6acac65da87f50eacca1b2/contracts/GnosisSafe.sol#L185
https://github.com/daseinsucks/MultisigWIP/blob/9e82202183772a053f6acac65da87f50eacca1b2/contracts/GnosisSafe.sol#L195




https://github.com/daseinsucks/MultisigWIP/blob/9e82202183772a053f6acac65da87f50eacca1b2/contracts/GnosisSafe.sol#L214
https://github.com/daseinsucks/MultisigWIP/blob/9e82202183772a053f6acac65da87f50eacca1b2/contracts/GnosisSafe.sol#L218
