### ISSUE TITLE
get two decoded elements

### ISSUE THREAD

**Issue by JackBekket** [daseinsucks/MultisigWIP#3]
https://github.com/daseinsucks/MultisigWIP/blob/8812577e9b2dec91e8c05c3b1092f83220d45ae6/contracts/GnosisSafe.sol#L245

да, просто там будет unused local variable, но да, надо как-то это пофиксить

**Comment by daseinsucks** [comment]
https://github.com/daseinsucks/MultisigWIP/blob/9e82202183772a053f6acac65da87f50eacca1b2/contracts/GnosisSafe.sol#L261-L264

Адрес токена мы не из data берем, а вот отсюда
https://github.com/daseinsucks/MultisigWIP/blob/9e82202183772a053f6acac65da87f50eacca1b2/contracts/GnosisSafe.sol#L235-L236

Так что передавать надо два аргумента, адрес токена (для адреса токена) и data (для расчета количества).
