### ISSUE TITLE
calculateData2 check

### ISSUE THREAD

**Issue by JackBekket** [daseinsucks/MultisigWIP#4]
https://github.com/daseinsucks/MultisigWIP/blob/8812577e9b2dec91e8c05c3b1092f83220d45ae6/contracts/GnosisSafe.sol#L257

ну если это не токен трансфер, то мы просто в основной функции дернем execute() вместо executePayload(), поэтому кажется проверка на адрес тут не обязательна

с другой стороны тут должна быть проверка как раз на methodID, и если это не тот methodID, то сразу ревертить, потому что в таком случае мы можем попытаться расшифровать какую-то хуйню вместо `_address, _amount`, т.е. там тот самый *undefined behaviour*, поэтому лучше прост чекать тут метод перед всем

**Comment by daseinsucks** [comment]
https://github.com/daseinsucks/MultisigWIP/blob/9e82202183772a053f6acac65da87f50eacca1b2/contracts/GnosisSafe.sol#L235-L246

После проверки адреса токена, если он совпадает с нужным нам, проверка на метод проходит вот здесь. Можно было бы в execTransaction, но stack to deep/10, да и особо роли место проверки не играет, как мне кажется, так и так реверт выбьет.
